### ISSUE TITLE
Review IOU04 / MIO04 - WIP

### ISSUE THREAD

**Issue by FranziskaKnoedtel** [ci4rail/docs#33]
Collected Remarks:

* {{ example_service_name }} in [Connect to the CAN Function - Code Example](https://github.com/ci4rail/docs/blob/main/docs/_includes/content/io4edge/canl2/detailed-description.md#connect-to-the-can-function) should be in quotes
* sample point description in [CAN Config](https://github.com/ci4rail/docs/blob/main/docs/_includes/content/io4edge/iou04-front/can-config-connect.md): "Sampling Point is 0.625 (62.5%)"
* In [Controlling the Stream](https://github.com/ci4rail/docs/blob/main/docs/_includes/content/io4edge/canl2/detailed-description.md#controlling-the-stream):
Mention all default configurations of start stream
"However, subsequent buckets may contain more samples, if already more samples are in the internal buffer." for now this sentence is not correct
* In [Bus Off Handling](https://github.com/ci4rail/docs/blob/main/docs/_includes/content/io4edge/canl2/detailed-description.md#bus-off-handling):
  Typo: "When bus off state is entered, The firmware waits 3 seconds and the resets the CAN controller." -> "When bus off state is entered, the firmware waits 3 seconds and then resets the CAN controller."

**Comment by KlausPopp** [comment]
all remarks implemented
